/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewAtencionCliente;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Jose El Asmar
 */
public class ConsultarListaPaciente extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarListaPaciente
     */
    public ConsultarListaPaciente() {
        initComponents(); setIconImage(getIconImage());
    }

       @Override
  public Image getIconImage () {  
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Image/Logo.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcionEmergencia = new javax.swing.ButtonGroup();
        lbTituto = new javax.swing.JLabel();
        TablaEmergencia = new javax.swing.JPanel();
        Regresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Mayor = new javax.swing.JRadioButton();
        Menor = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        ModificarDato = new javax.swing.JButton();
        EliminarPaciente = new javax.swing.JButton();
        EditarDescripcion = new javax.swing.JButton();
        cargarDescripcion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTituto.setBackground(new java.awt.Color(255, 255, 255));
        lbTituto.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lbTituto.setForeground(new java.awt.Color(255, 255, 255));
        lbTituto.setText("Lista de Pacientes por Atender");
        getContentPane().add(lbTituto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        TablaEmergencia.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout TablaEmergenciaLayout = new javax.swing.GroupLayout(TablaEmergencia);
        TablaEmergencia.setLayout(TablaEmergenciaLayout);
        TablaEmergenciaLayout.setHorizontalGroup(
            TablaEmergenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        TablaEmergenciaLayout.setVerticalGroup(
            TablaEmergenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        getContentPane().add(TablaEmergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 592, 461));

        Regresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Regresar.setText("Regresar");
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Tabla de Emergencia");

        OpcionEmergencia.add(Mayor);
        Mayor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Mayor.setText("Emergencia Mayor");

        OpcionEmergencia.add(Menor);
        Menor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Menor.setText("Emergencia Menor");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Descripción del paciente");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Mayor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Menor)))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mayor)
                    .addComponent(Menor))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, 300));

        ModificarDato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ModificarDato.setText("Modificar Datos");
        getContentPane().add(ModificarDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 190, 40));

        EliminarPaciente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EliminarPaciente.setText("Eliminar Paciente ");
        getContentPane().add(EliminarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 210, 40));

        EditarDescripcion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        EditarDescripcion.setText("Editar Descripción");
        getContentPane().add(EditarDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, -1));

        cargarDescripcion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cargarDescripcion.setText("Cargar Descripción");
        getContentPane().add(cargarDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, 165, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/l.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarListaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarListaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarListaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarListaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarListaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton EditarDescripcion;
    public javax.swing.JButton EliminarPaciente;
    public javax.swing.JRadioButton Mayor;
    public javax.swing.JRadioButton Menor;
    public javax.swing.JButton ModificarDato;
    public javax.swing.ButtonGroup OpcionEmergencia;
    public javax.swing.JButton Regresar;
    public javax.swing.JPanel TablaEmergencia;
    public javax.swing.JButton cargarDescripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTituto;
    public javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
