/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewAtencionCliente;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Jose El Asmar
 */
public class IngresarPaciente extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarListaPaciente
     */
    public IngresarPaciente() {
        initComponents(); setIconImage(getIconImage());
    }

       @Override
  public Image getIconImage () {  
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Image/Logo.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcionIngreso = new javax.swing.ButtonGroup();
        lbTituto = new javax.swing.JLabel();
        TablaEmergencia = new javax.swing.JPanel();
        Regresar = new javax.swing.JButton();
        VerificarMaterial = new javax.swing.JButton();
        IngresarPaciente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ambulatorio = new javax.swing.JRadioButton();
        Clinica = new javax.swing.JRadioButton();
        VerificarPersonal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTituto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTituto.setForeground(new java.awt.Color(255, 255, 255));
        lbTituto.setText("Ingresar Paciente al Hospital");
        getContentPane().add(lbTituto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        TablaEmergencia.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout TablaEmergenciaLayout = new javax.swing.GroupLayout(TablaEmergencia);
        TablaEmergencia.setLayout(TablaEmergenciaLayout);
        TablaEmergenciaLayout.setHorizontalGroup(
            TablaEmergenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TablaEmergenciaLayout.setVerticalGroup(
            TablaEmergenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(TablaEmergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 592, 461));

        Regresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Regresar.setText("Regresar");
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 110, -1));

        VerificarMaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VerificarMaterial.setText("Verificar Material Médico");
        VerificarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarMaterialActionPerformed(evt);
            }
        });
        getContentPane().add(VerificarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 220, 40));

        IngresarPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IngresarPaciente.setText("Ingresar Paciente");
        getContentPane().add(IngresarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 220, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Tipo de Ingreso");

        OpcionIngreso.add(Ambulatorio);
        Ambulatorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ambulatorio.setText("Ambulatorio");
        Ambulatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmbulatorioActionPerformed(evt);
            }
        });

        OpcionIngreso.add(Clinica);
        Clinica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Clinica.setText("Clínica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ambulatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Clinica)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ambulatorio)
                    .addComponent(Clinica))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 290, -1));

        VerificarPersonal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VerificarPersonal.setText("Verificar Personal Medico");
        VerificarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(VerificarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 220, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/l.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 2, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerificarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerificarMaterialActionPerformed

    private void AmbulatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmbulatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmbulatorioActionPerformed

    private void VerificarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerificarPersonalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton Ambulatorio;
    public javax.swing.JRadioButton Clinica;
    public javax.swing.JButton IngresarPaciente;
    public javax.swing.ButtonGroup OpcionIngreso;
    public javax.swing.JButton Regresar;
    public javax.swing.JPanel TablaEmergencia;
    public javax.swing.JButton VerificarMaterial;
    public javax.swing.JButton VerificarPersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbTituto;
    // End of variables declaration//GEN-END:variables
}
