/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewPlantillaMedica;

/**
 *
 * @author Jose El Asmar
 */
public class OpcionMedico extends javax.swing.JPanel {

    /**
     * Creates new form OpcionMedico
     */
    public OpcionMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcionTrabajo = new javax.swing.ButtonGroup();
        Ambulatorio = new javax.swing.JRadioButton();
        Clinica = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        OpcionTrabajo.add(Ambulatorio);
        Ambulatorio.setText("Ambulatorio");

        OpcionTrabajo.add(Clinica);
        Clinica.setText("Clínica");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Ambulatorio)
                .addGap(31, 31, 31)
                .addComponent(Clinica)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ambulatorio)
                    .addComponent(Clinica))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton Ambulatorio;
    public javax.swing.JRadioButton Clinica;
    public javax.swing.ButtonGroup OpcionTrabajo;
    // End of variables declaration//GEN-END:variables
}
